testConfig:
  queriesDirectory: NOTUSEDYET
  outputDirectory: test-output
  plugins:
    - json:test-output/reports/cucumber.json
    - framework.core.reports.CucumberEventListener
  returnScreenshotOnEveryAction: false
  scriptTimeout: 120
  pageLoadTimeout: 120
  #screenshotWidth: 640
  #screenshotHeight: 480

driverConfig:
  desiredCapabilities:
    browserName: chrome
    version: 60
    platform: WINDOWS
    javascriptEnabled: true
    acceptSslCerts: true
    handlesAlerts: true
    cssSelectorsEnabled: true
    unexpectedAlertBehaviour: accept
    explicitTimeout: 60
    pollingTime: 500
  ie:
    enablePersistantHovering: false
  chrome:
    path: "C:\\Drivers\\chromedriver_win32\\chromedriver.exe"
    args:
      --disable-extensions
      --disable-infobars
  firefox:
  #    path: "C:\\Drivers\\geckodriver-v0.14.0-win64\\geckodriver.exe"
  #    browser.download.dir: System.getProperty('user.home') + '/Downloads'
  #    browser.download.folderList: 2
  #    browser.download.manager.showWhenStarting: false
  #    browser.helperApps.alwaysAsk.force: false
  #    browser.download.manager.closeWhenDone: true
  #    browser.download.manager.focusWhenStarting: false
  #    pdfjs.disabled: true
  edge:
  safari:
  remote:

environments:
  oracle_fusion:
    webUrl: https://hcczdev-test.login.em3.oraclecloud.com