testConfig:
  queriesDirectory: NOTUSEDYET
  outputDirectory: test-output
  plugins:
    - json:test-output/reports/cucumber.json
    - framework.core.reports.CucumberEventListener
  returnScreenshotOnEveryAction: false
  scriptTimeout: 60
  pageLoadTimeout: 60
  #screenshotWidth: 640
  #screenshotHeight: 480

driverConfig:
  desiredCapabilities:
    browserName:
  chrome:
    #path: "C:\\Drivers\\chromedriver_win32\\chromedriver.exe"
    args:
      --disable-extensions
      --disable-infobars
  firefox:
  #    path: "C:\\Drivers\\geckodriver-v0.14.0-win64\\geckodriver.exe"
  #    browser.download.dir: System.getProperty('user.home') + '/Downloads'
  #    browser.download.folderList: 2
  #    browser.download.manager.showWhenStarting: false
  #    browser.helperApps.alwaysAsk.force: false
  #    browser.download.manager.closeWhenDone: true
  #    browser.download.manager.focusWhenStarting: false
  #    pdfjs.disabled: true
  ie:
    enablePersistantHovering: false
  edge:
  safari:
  remote:

environments:
  oracle_fusion_dev:
    webUrl: https://hcczdev-dev.login.em3.oraclecloud.com
  oracle_fusion_cognizant:
    webUrl: https://hcczdev-test.login.em3.oraclecloud.com
  oracle_fusion_test:
    webUrl: https://ecqg-test.fa.us2.oraclecloud.com/hcmUI/faces/FuseWelcome
  